[global]
#server_port = 3000 # (default = 3000)
#cashflow_limit = 200 # (default = 200)
#enable_security_charts = true # (default = false)
#disable_auto_taxes = false # (default = false)
#disable_sessions = false # (default = false)
#disable_update_accounts_on_login = false # (default = false)
[db]
# choices are "sqlite" or "mysql"
db = "sqlite"
# name is path to Database file (sqlite) or Database name (mysql)
name = "db/gobook_test.db"
# below only used with mysql
password = "passwd"
host = "127.0.0.1"
port = 3306
